### PR TITLE
Cmake: Add a CMakeLists

### LINKED ISSUE #311: Provide CMakeLists
For building & compiling with different compilers a CMakeLists.txt would be very useful.

### PR DESCRIPTION
**Pull request by 1480c1**
Closes #311 

I've only added the basic parts for it and only did what `make all` and `make install` does. Nothing else special added since this is just a basic one.

It's possible to add the other executables and stuff, but it seemed very unwieldy to do with the current file structure.

Went with a single file list since it seems that there were a lot
of going in between folders in the makefiles, which was pretty
ugly imo since it was hard to actually tell what line meant what.

Later on, I might try to improve it

### CODE REVIEW

**Comment by 1480c1** [comment]
I wish it was a cake list

**Comment by kylophone** [comment]
I would wait a minute on this. I have another patch on the way which reorganizes some of the lib code, and uses meson as a build system.

**Comment by 1480c1** [comment]
If all of the features can be implemented in the meson build system, then that would be great as that could mean that cmake doesn't have to be added since most of the things cmake can do, meson can also do, or the cmake part can be based on the meson.build file.

Although personally I don't have much knowledge about meson since I've never really had much of a good experience with python on windows in general

**Comment by kylophone** [comment]
> I would wait a minute on this. I have another patch on the way which reorganizes some of the lib code, and uses meson as a build system.

#379

**Comment by kylophone** [comment]
> > I would wait a minute on this. I have another patch on the way which reorganizes some of the lib code, and uses meson as a build system.
> 
> #379

Replaced by #384.

**Comment by kylophone** [comment]
#384 merged.

**Pull request closed without merging**
