### PR TITLE
rename metrics to features

### PR DESCRIPTION
**Pull request by slhck**
"Metrics" is ambiguous. The term "features" should be consistently used.

### CODE REVIEW

**Comment by li-zhi** [comment]
@slhck In my view, a feature is an *element* that can guide the prediction of a *metric*. To put it more concretely, the inputs to VMAF's SVR model are considered as *features*. A metric can be used as a feature for another metric, but not the other way around. In other words: *features* is a superset of *metrics*. Would you agree with this interpretation? If yes, I think it is best to keep the current wording. Happy to discuss.

**Comment by slhck** [comment]
I agree with you in principle.

My change was motivated by somewhat inconsistent usage of that terminology. Consider users coming from the ffmpeg libvmaf filter documentation, which talks about features that can be enabled but does not list them. (The improvement of that documentation itself is a more general issue we have discussed in another GitHub thread.) The documentation for VMAF itself should, in my opinion, make these features more discoverable. Otherwise there is no link between what is written in the ffmpeg documentation and what the user can find here.

How would you suggest to address this issue?

**Comment by li-zhi** [comment]
Thanks for the explanation. With this context, I think I am more convinced that the changes are needed. We just need to have a clarification on the "features is a superset of metrics" aspect. For example, the statement "Features are individual metrics that VMAF models may use to provide a quality score. Features can be enabled individually (e.g., when using VMAF via FFmpeg)." could be updated to "Features are individual inputs that (VMAF) models may use to provide a quality metric score. Note that an existing quality metric can serve as a feature of a new quality metric. Features can be enabled individually (e.g., when using VMAF via FFmpeg)."

**Comment by slhck** [comment]
Thanks, that makes perfect sense. Pushed with that change!

**Pull request merged**
