### PR TITLE
libvmaf: build with meson

### PR DESCRIPTION
**Pull request by kylophone**
Hi,

This PR is mostly just a reworking of the libvmaf build system. The Makefiles and Visual Studio files have been stripped and replaced with meson files for cross-platform building. See `libvmaf/README.md` and/or `.travis.yml` for build instructions. A few of the niceties we now have are: 

* Normalized cross-platform build system for dynamic/static libs. Executables, too: `vmafossexec` and the accessory feature extraction executables used from Python.
* Debug and release builds.
* Templatized library versioning, including soname versioning.
* Templatized pkg_config.
* VCS based versioning for pre-tagged releases.
* Integrated builds for testing, documentation.

While most of this PR was moving files around and fixing up the build system, there were a few very small changes. The diff is pretty large with all the deletions, so I'll highlight a few points here.

* All `libvmaf` source files are now found under the `libvmaf/` directory. 
* `libsvm` was removed from the `libvmaf` tree. This is a dependency from the Python side, not the `libvmaf` side. (Not part of this PR, but eventually we should try to remove this duplication completely.)
* Private classes were moved from the published `libvmaf.h` header file into appropriate internal headers.
* `pthreads` is no longer included in-tree. This is a dependency that isn't needed for POSIX, but sort of helpful for Windows. The current Windows build should work fine if you bring your own pthreads. When `ptools` goes away (see #383), we will provide a simple Win32 threads wrapper for the libvmaf threading. This work is expected soon.
* New location of the accessory feature extraction executables updated on the Python side. 

This is an initial step towards a v2.0 API (see #381). Note, that this specific PR contains no breaking API changes. All tests are passing in Travis.

Questions and comments are welcome.

Thanks,
Kyle

### CODE REVIEW

**Comment by 1480c1** [comment]
Would it not be possible to add a top level meson.build that just links to the main one? That way people who clone the repository can quickly build it without an extra step of changing their directory.

Also, recommendation: Mention removal of makefile and sln file and addition to making meson the main buildsystem in the changelog so downstream can know

**Comment by kylophone** [comment]
> Would it not be possible to add a top level meson.build that just links to the main one? That way people who clone the repository can quickly build it without an extra step of changing their directory.

https://github.com/Netflix/vmaf/pull/379#issuecomment-541962683
Maybe a top-level `./build.sh` is called for, though.

> Also, recommendation: Mention removal of makefile and sln file and addition to making meson the main buildsystem in the changelog so downstream can know

Good idea. I'll add this.

**Comment by dougsillars** [comment]
I followed the new instructions to build libvmaf for adding it into FFMPEG, but when I attempt to compile FFMPEG, I'm getting:
"ERROR: libvmaf >= 1.3.9 not found using pkg-config"

AS far as I can tell, the library files are are copied into the correct directories, and pkg-config has all of the directories in its path.  Any ideas?  Using an Ubuntu EC2 instance.

Thanks!

**Comment by 1480c1** [comment]
You should probably look into the ffbuild/config.log file and check

**Comment by dougsillars** [comment]
Thanks - The last 5 lines literally say the exact same thing:
/tmp/ffconf.kklNqttU/test.c:1:10: fatal error: libvmaf.h: No such file or directory
 #include <libvmaf.h>
          ^~~~~~~~~~~
compilation terminated.
ERROR: libvmaf >= 1.3.9 not found using pkg-config

**Comment by audelaney** [comment]
@dougsillars I was having this same issue, and @1480c1 fixed that part with #408 . FFmpeg now compiles for me, but reports `ffmpeg: error while loading shared libraries: libvmaf.so: cannot open shared object file: No such file or directory` when attempting to run. My updated libvmaf.pc contains
```
prefix=/usr/local
libdir=${prefix}/lib/x86_64-linux-gnu
includedir=${prefix}/include

Name: libvmaf
Description: VMAF, Video Multimethod Assessment Fusion
Version: 1.3.16
Libs: -L${libdir} -lvmaf
Libs.private: -pthread
Cflags: -I${includedir}/libvmaf
```
And my /usr/local/lib/x86_64-linux-gnu does indeed contain the libvmaf.a and libvmaf.so files.

**Comment by 1480c1** [comment]
Try
```bash
LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/usr/local/lib/x86_64-linux-gnu
export LD_LIBRARY_PATH
```
then run ffmpeg

I think ffmpeg is not able to find the shared library because there is nothing pointing to it

**Comment by audelaney** [comment]
> ```shell
> LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/usr/local/lib/x86_64-linux-gnu
> ```

This did the trick for me. Thanks

**Pull request merged**
