### PR TITLE
Feature/add cambi

### PR DESCRIPTION
**Pull request by li-zhi**

### CODE REVIEW

**Comment by kylophone** [comment]
Since we're adding `VMAF_PIX_FMT_YUV400P` to the public API, we'll need to bump the minor version whenever we cut the new release. Also, #863 will need to be addressed before the next release as well.

**Comment by kylophone** [comment]
Tested with UBSAN and ASAN, no problems. I noticed that `convert_8b_luma_to_10b` is unused:

```sh
../src/feature/cambi.c:347:13: warning: unused function 'convert_8b_luma_to_10b' [-Wunused-function]  
```

**Comment by li-zhi** [comment]
> Tested with UBSAN and ASAN, no problems. I noticed that `convert_8b_luma_to_10b` is unused:
> 
> ```shell
> ../src/feature/cambi.c:347:13: warning: unused function 'convert_8b_luma_to_10b' [-Wunused-function]  
> ```

Removed convert_8b_luma_to_10b.

**Comment by li-zhi** [comment]
> Since we're adding `VMAF_PIX_FMT_YUV400P` to the public API, we'll need to bump the minor version whenever we cut the new release. Also, #863 will need to be addressed before the next release as well.

@kylophone Adding `VMAF_PIX_FMT_YUV400P` seems fine as @joelsole uses this format only for an internal initialization in cambi. The public API only supports 420/422/444 still. See: https://github.com/Netflix/vmaf/blob/master/libvmaf/tools/cli_parse.c#L127-L144
So we are not breaking anything.

#863 is different, as @HolyWu seems trying to directly access the methods underneath. We may later consider generalizing the API to support 400 (or "gray" in ffmpeg lingo) but it should not block CAMBI release.

**Comment by kylophone** [comment]
> > Since we're adding `VMAF_PIX_FMT_YUV400P` to the public API, we'll need to bump the minor version whenever we cut the new release. Also, #863 will need to be addressed before the next release as well.
> 
> @kylophone Adding `VMAF_PIX_FMT_YUV400P` seems fine as @joelsole uses this format only for an internal initialization in cambi. The public API only supports 420/422/444 still. See: https://github.com/Netflix/vmaf/blob/master/libvmaf/tools/cli_parse.c#L127-L144 So we are not breaking anything.

I am talking about the libvmaf C API. This is an addition to a public enum. It is a backwards compatible change, but not a forwards compatible one. Therefore minor library version should be bumped.

https://github.com/Netflix/vmaf/blob/f5e984375925d88edb8fb613db7496be642f8450/libvmaf/include/libvmaf/picture.h#L33

**Comment by kylophone** [comment]
> > When you squash this, make sure you give the authors attribution in the commit.
> 
> @kylophone I don't plan to squash, but I've updated the commit message to indicate the authors of the code.

You can add multiple authors to the commit if you'd like.

**Pull request merged**
