### PR TITLE
meson: use library() and fix external builds

### LINKED ISSUE #557: create dynamic link library of libvmaf
current libvmaf only support static link library. is it possible to create an option to build the library as dynamic link library?

### LINKED ISSUE #752: external builds fail due to undef ref to embedded model symbols
running
```bash
git clone https://github.com/Netflix/vmaf
meson setup --buildtype release -Dlibdir=lib vmaf-build vmaf/libvmaf
sudo -E meson install -C vmaf-build
```
fails on meson install with the following:
```c
[93/120] Linking target src/libvmaf.so.1.0.0.
FAILED: src/libvmaf.so.1.0.0 
c++  -o src/libvmaf.so.1.0.0 'src/25a6634@@vmaf@sha/meson-generated_.._vmaf_v0.6.1.json.c.o' 'src/25a6634@@vmaf@sha/meson-generated_.._vmaf_b_v0.6.3.json.c.o' 'src/25a6634@@vmaf@sha/meson-generated_.._vmaf_v0.6.1neg.json.c.o' 'src/25a6634@@vmaf@sha/libvmaf.c.o' 'src/25a6634@@vmaf@sha/compute_vmaf.c.o' 'src/25a6634@@vmaf@sha/predict.c.o' 'src/25a6634@@vmaf@sha/model.c.o' 'src/25a6634@@vmaf@sha/svm.cpp.o' 'src/25a6634@@vmaf@sha/picture.c.o' 'src/25a6634@@vmaf@sha/mem.c.o' 'src/25a6634@@vmaf@sha/output.c.o' 'src/25a6634@@vmaf@sha/fex_ctx_vector.c.o' 'src/25a6634@@vmaf@sha/thread_pool.c.o' 'src/25a6634@@vmaf@sha/dict.c.o' 'src/25a6634@@vmaf@sha/opt.c.o' 'src/25a6634@@vmaf@sha/ref.c.o' 'src/25a6634@@vmaf@sha/read_json_model.c.o' 'src/25a6634@@vmaf@sha/pdjson.c.o' 'src/25a6634@@x86_avx2@sta/feature_common_convolution_avx.c.o' 'src/25a6634@@x86_avx2@sta/feature_x86_motion_avx2.c.o' 'src/25a6634@@x86_avx2@sta/feature_x86_vif_avx2.c.o' 'src/25a6634@@x86_avx2@sta/feature_x86_adm_avx2.c.o' 'src/25a6634@@libvmaf_feature@sta/feature_picture_copy.c.o' 'src/25a6634@@libvmaf_feature@sta/feature_integer_psnr.c.o' 'src/25a6634@@libvmaf_feature@sta/feature_third_party_xiph_psnr_hvs.c.o' 'src/25a6634@@libvmaf_feature@sta/feature_feature_extractor.c.o' 'src/25a6634@@libvmaf_feature@sta/feature_alias.c.o' 'src/25a6634@@libvmaf_feature@sta/feature_integer_adm.c.o' 'src/25a6634@@libvmaf_feature@sta/feature_feature_collector.c.o' 'src/25a6634@@libvmaf_feature@sta/feature_integer_motion.c.o' 'src/25a6634@@libvmaf_feature@sta/feature_integer_vif.c.o' 'src/25a6634@@libvmaf_feature@sta/feature_ciede.c.o' 'src/25a6634@@libvmaf_feature@sta/feature_common_alignment.c.o' 'src/25a6634@@libvmaf_feature@sta/feature_float_ssim.c.o' 'src/25a6634@@libvmaf_feature@sta/feature_float_ms_ssim.c.o' 'src/25a6634@@libvmaf_feature@sta/feature_ssim.c.o' 'src/25a6634@@libvmaf_feature@sta/feature_ms_ssim.c.o' 'src/25a6634@@libvmaf_feature@sta/feature_iqa_decimate.c.o' 'src/25a6634@@libvmaf_feature@sta/feature_iqa_ssim_tools.c.o' 'src/25a6634@@libvmaf_feature@sta/feature_iqa_math_utils.c.o' 'src/25a6634@@libvmaf_feature@sta/feature_iqa_convolve.c.o' 'src/25a6634@@libvmaf_cpu@sta/cpuid.obj' 'src/25a6634@@libvmaf_cpu@sta/cpu.c.o' 'src/25a6634@@libvmaf_cpu@sta/x86_cpu.c.o' -Wl,--as-needed -Wl,--no-undefined -Wl,-O1 -shared -fPIC -Wl,--start-group -Wl,-soname,libvmaf.so.1 -pthread -lm -Wl,--end-group
/usr/bin/ld: src/25a6634@@vmaf@sha/model.c.o:(.data.rel.ro+0x8): undefined reference to `___src_______model_vmaf_v0_6_1_json'
/usr/bin/ld: src/25a6634@@vmaf@sha/model.c.o:(.data.rel.ro+0x10): undefined reference to `___src_______model_vmaf_v0_6_1_json_len'
/usr/bin/ld: src/25a6634@@vmaf@sha/model.c.o:(.data.rel.ro+0x20): undefined reference to `___src_______model_vmaf_b_v0_6_3_json'
/usr/bin/ld: src/25a6634@@vmaf@sha/model.c.o:(.data.rel.ro+0x28): undefined reference to `___src_______model_vmaf_b_v0_6_3_json_len'
/usr/bin/ld: src/25a6634@@vmaf@sha/model.c.o:(.data.rel.ro+0x38): undefined reference to `___src_______model_vmaf_v0_6_1neg_json'
/usr/bin/ld: src/25a6634@@vmaf@sha/model.c.o:(.data.rel.ro+0x40): undefined reference to `___src_______model_vmaf_v0_6_1neg_json_len'
collect2: error: ld returned 1 exit status
...

[95/120] Linking target tools/vmafossexec.
FAILED: tools/vmafossexec 
c++  -o tools/vmafossexec 'tools/f9d35d4@@vmafossexec@exe/main.cpp.o' 'tools/f9d35d4@@vmafossexec@exe/read_frame.c.o' -Wl,--as-needed -Wl,--no-undefined -Wl,-O1 -Wl,--start-group src/libvmaf.a -pthread -lm -Wl,--end-group '-Wl,-rpath,$ORIGIN/../src' -Wl,-rpath-link,/code/vmaf-build/src
/usr/bin/ld: src/libvmaf.a(model.c.o):(.data.rel.ro+0x8): undefined reference to `___src_______model_vmaf_v0_6_1_json'
/usr/bin/ld: src/libvmaf.a(model.c.o):(.data.rel.ro+0x10): undefined reference to `___src_______model_vmaf_v0_6_1_json_len'
/usr/bin/ld: src/libvmaf.a(model.c.o):(.data.rel.ro+0x20): undefined reference to `___src_______model_vmaf_b_v0_6_3_json'
/usr/bin/ld: src/libvmaf.a(model.c.o):(.data.rel.ro+0x28): undefined reference to `___src_______model_vmaf_b_v0_6_3_json_len'
/usr/bin/ld: src/libvmaf.a(model.c.o):(.data.rel.ro+0x38): undefined reference to `___src_______model_vmaf_v0_6_1neg_json'
/usr/bin/ld: src/libvmaf.a(model.c.o):(.data.rel.ro+0x40): undefined reference to `___src_______model_vmaf_v0_6_1neg_json_len'
collect2: error: ld returned 1 exit status
[96/120] Linking target tools/vmaf.
FAILED: tools/vmaf 
c++  -o tools/vmaf 'tools/f9d35d4@@vmaf@exe/vmaf.c.o' 'tools/f9d35d4@@vmaf@exe/cli_parse.c.o' 'tools/f9d35d4@@vmaf@exe/y4m_input.c.o' 'tools/f9d35d4@@vmaf@exe/vidinput.c.o' 'tools/f9d35d4@@vmaf@exe/yuv_input.c.o' -Wl,--as-needed -Wl,--no-undefined -Wl,-O1 -Wl,--start-group src/libvmaf.a -pthread -lm -Wl,--end-group '-Wl,-rpath,$ORIGIN/../src' -Wl,-rpath-link,/code/vmaf-build/src
/usr/bin/ld: src/libvmaf.a(model.c.o):(.data.rel.ro+0x8): undefined reference to `___src_______model_vmaf_v0_6_1_json'
/usr/bin/ld: src/libvmaf.a(model.c.o):(.data.rel.ro+0x10): undefined reference to `___src_______model_vmaf_v0_6_1_json_len'
/usr/bin/ld: src/libvmaf.a(model.c.o):(.data.rel.ro+0x20): undefined reference to `___src_______model_vmaf_b_v0_6_3_json'
/usr/bin/ld: src/libvmaf.a(model.c.o):(.data.rel.ro+0x28): undefined reference to `___src_______model_vmaf_b_v0_6_3_json_len'
/usr/bin/ld: src/libvmaf.a(model.c.o):(.data.rel.ro+0x38): undefined reference to `___src_______model_vmaf_v0_6_1neg_json'
/usr/bin/ld: src/libvmaf.a(model.c.o):(.data.rel.ro+0x40): undefined reference to `___src_______model_vmaf_v0_6_1neg_json_len'
collect2: error: ld returned 1 exit status
[98/120] Compiling C++ object 'test/9f86d08@@test_predict@exe/.._src_svm.cpp.o'.
ninja: build stopped: subcommand failed.
Could not rebuild vmaf-build/
```

grepping
```c
grep -R ___src_______model_vmaf_v0_6_1_json vmaf-build/ 
grep: vmaf-build/src/libvmaf.so: No such file or directory
Binary file vmaf-build/src/25a6634@@vmaf@sha/model.c.o matches
Binary file vmaf-build/src/libvmaf.a matches
grep: vmaf-build/src/libvmaf.so.1: No such file or directory
Binary file vmaf-build/test/9f86d08@@test_predict@exe/.._src_model.c.o matches
Binary file vmaf-build/test/9f86d08@@test_model@exe/test_model.c.o matches
```

running `ninja -v`, I see
```c
ninja: Entering directory `vmaf-build/'
[1/120] /usr/bin/xxd --include ../vmaf/libvmaf/src/../../model/vmaf_v0.6.1.json src/vmaf_v0.6.1.json.c
[2/120] /usr/bin/xxd --include ../vmaf/libvmaf/src/../../model/vmaf_v0.6.1neg.json src/vmaf_v0.6.1neg.json.c
...
```

### PR DESCRIPTION
**Pull request by 1480c1**
Use `library()` so the `--default-library`  flag will have an effect, fixes #557 and an issue in #613

also fixes #752

### CODE REVIEW

**Comment by 1480c1** [comment]
I guess github actions is updating their stuff

**Comment by kylophone** [comment]
@1480c1, finally got around to testing this. Sorry for the delay! Can we please keep the `vmaf` tool statically linked by default? Other than that, I think this looks good. Thanks for fixes.

**Comment by 1480c1** [comment]
> Can we please keep the `vmaf` tool statically linked by default?

since we are using `library()` instead of `both_libraries()`, the object doesn't have a static library associated with it by default, the user would need to choose to create, and thus link, a static library through the `--default-library static` flag. In the case where they use `--default-library both`, I believe meson will choose the shared library by default, I am not sure if there's a way to detect if the object returned has a static version in a `both` scenario and link to it, maybe best that could be done would be to have a different path if `default-library` is `both`

**Comment by kylophone** [comment]
> , I believe meson will choose the shared library by default, I am not sure if there's a way to dete

Hmm, I see. I guess just updating the build docs include `--default-library static` if desired. Also we'll want to update this in our CI runners to make sure that the artifacts we're uploading are statically linked.

**Comment by 1480c1** [comment]
I am currently testing a way to detect the `default_library` option and choosing the static version when applied, do hold before merging

**Comment by kylophone** [comment]
> I am currently testing a way to detect the `default_library` option and choosing the static version when applied, do hold before merging

Yep, will stand by.

**Comment by 1480c1** [comment]
changing `link_with : libvmaf` to `link_with : get_option('default_library') == 'both' ? libvmaf.get_static_lib() : libvmaf` now results with

| --default-library | ninja test | libvmaf | `ldd libvmaf/build/tools/vmaf` |
| -- | -- | -- | -- |
| none | OK | .so | `/code/vmaf/libvmaf/build/tools/../src/libvmaf.so.1` |
| `static` | OK | .a | no `*vmaf.so*` |
| `shared` | OK | .so | `/code/vmaf/libvmaf/build/tools/../src/libvmaf.so.1` |
| `both` | OK | .a and .so | no `*vmaf.so*` |

So I guess the only thing left would be, do we want `static` to be the default option on `none`, or the current `shared`?

**Comment by 1480c1** [comment]
I'm going to set the default to doing both to match what we previously had

**Comment by 1480c1** [comment]
@kylophone ready for review

**Comment by kylophone** [comment]
Alright, I've tested and merged. Thanks for being patient!

**Pull request merged**
