### PR TITLE
Actions: Add libvmaf.yml

### PR DESCRIPTION
**Pull request by 1480c1**
Replicates some of the jobs in travis-ci

### CODE REVIEW

**Comment by 1480c1** [comment]
How it looks on my repository https://github.com/1480c1/vmaf/actions/runs/88645912

**Comment by li-zhi** [comment]
It looks like it ran the extratests (meant for tests with external dependency such as FFmpeg and Matlab). I added conditional skip for them. Please try again after rebasing master.

**Comment by 1480c1** [comment]
Should I change this to always run on push and prs? Right now it's only running if there was a change to any of the workflows or under the libvmaf subfolder

**Comment by li-zhi** [comment]
I am not familiar with the github workflow. How does it do differently than the travis CI? why do we need it since we already have travis CI?

**Comment by 1480c1** [comment]
I am mainly thinking about moving some of the jobs from travis-ci to github ci, with the main purpose of spreading the number of jobs that are currently being run. Plus, I would consider github actions to have slightly better integration with pull requests since it will display a notification for each job separately rather than a single `continuous-integration/travis-ci/pr`


Also, I have a feeling that the reason why the python job is failing is that it can't find ffmpeg

**Comment by 1480c1** [comment]
For example, from a different repo
image

**Comment by li-zhi** [comment]
In this case, we can migrate to github ci and retire travis ci.

I pushed some changes to master. Hopefully it is going to fix the issue.

**Comment by li-zhi** [comment]
@1480c1 would you also help add a "build" badge to the README.md for github ci?

**Comment by 1480c1** [comment]
> @1480c1 would you also help add a "build" badge to the README.md for github ci?

Sure, I can do that

**Pull request merged**
