### PR TITLE
PSNR-HVS: increase weights of medium frequencies

### LINKED ISSUE #921: PSNR-HVS: fix JPEG
In [comparison by WEBP2 team](https://storage.googleapis.com/demos.webmproject.org/webp/cmp/2021_08_10/plots.html) JPEG is too high and JPEG-XL is too low (but this looks like because of color bleeding). [VIFp](https://github.com/Netflix/vmaf/issues/826#issuecomment-781923811) with fine scale sigma_nsq=256 shows similar results. Apparently it's too much. Fix that by increasing weights of medium frequencies:

```
float csf_y[8][8]={
    {1.6193873005, 2.2901594831, 2.08509755623, 1.60392119708, 1.33660099757, 1.21509181597, 1.10462892361, 1.00420811237},
    {2.2901594831, 1.94321815382, 2.04793073064, 1.68731108984, 1.40609257487, 1.27826597715, 1.16205997923, 1.05641816294},
    {2.08509755623, 2.04793073064, 1.38801296701, 1.32191711144, 1.25896867756, 1.19901778815, 1.141921703, 1.03811063909},
    {1.60392119708, 1.68731108984, 1.32191711144, 1.2069677974, 1.14949314038, 1.09475537179, 0.99523215617, 0.79618572494},
    {1.33660099757, 1.40609257487, 1.25896867756, 1.14949314038, 1.04953721513, 0.95412474103, 0.79510395086, 0.58896588953},
    {1.21509181597, 1.27826597715, 1.19901778815, 1.09475537179, 0.95412474103, 0.77743497417, 0.57587775864, 0.44298289126},
    {1.10462892361, 1.16205997923, 1.141921703, 0.99523215617, 0.79510395086, 0.57587775864, 0.43190831898, 0.33223716845},
    {1.00420811237, 1.05641816294, 1.03811063909, 0.79618572494, 0.58896588953, 0.44298289126, 0.33223716845, 0.2399490661}
};
```

And decrease [strength of masking](https://github.com/Netflix/vmaf/blob/c8f54f566c3cabc103802f0f944b54d54f3c28a5/libvmaf/src/feature/third_party/xiph/psnr_hvs.c#L315-L316):

```
    s_mask = sqrt(s_mask * s_gvar) / 45.f;
    d_mask = sqrt(d_mask * d_gvar) / 45.f;
```

This shows similar result to VIFp with sigma_nsq=100 (still a little bit too much in my opinion), which is similar to DSSIM.

### PR DESCRIPTION
**Pull request by igv**
Closes #921

### CODE REVIEW

**Comment by netcazean** [comment]
#925

**Comment by kylophone** [comment]
These weights cannot be changed since they are used as part of the AOM CTC for testing during codec development. The weights came from daala and were used during the development of AV1. It is probably possible to switch to the non-default weights at runtime via an optional parameter. We need more information on why/how these weights are derived. Do you have any data that shows better correlation with subjective testing scores?

**Comment by igv** [comment]
> The weights came from daala and were used during the development of AV1

Maybe that's why AV1 smoothes high-medium frequencies so much (I know some people don't like that about this codec)?

**Comment by igv** [comment]
Slightly different variant of this matrix for "slightly higher MOS agreement":
```
    {1.6193873005, 2.2901594831, 2.0850975562, 1.895543233, 1.579619361, 1.316349467, 1.096957889, 0.914131575},
    {2.2901594831, 1.9432181538, 2.0479307306, 1.86175521, 1.551462675, 1.292885562, 1.077404635, 0.897837196},
    {2.0850975562, 2.0479307306, 1.494783195, 1.358893814, 1.235358012, 1.123052739, 1.020957035, 0.887788726},
    {1.895543233, 1.86175521, 1.358893814, 1.195826556, 1.087115051, 0.98828641, 0.898442191, 0.816765628},
    {1.579619361, 1.551462675, 1.235358012, 1.087115051, 0.956661245, 0.869692041, 0.790629128, 0.658857607},
    {1.316349467, 1.292885562, 1.123052739, 0.98828641, 0.869692041, 0.765328996, 0.637774163, 0.49059551},
    {1.096957889, 1.077404635, 1.020957035, 0.898442191, 0.790629128, 0.637774163, 0.478330622, 0.367946633},
    {0.914131575, 0.897837196, 0.887788726, 0.816765628, 0.658857607, 0.49059551, 0.367946633, 0.298956639}
```

**Comment by igv** [comment]
For "a slightly higher MOS agreement" they could just remove this redundant part:
```
                 for (j = (i == 0); j < 8; j++)
                     d_mask += dct_d[i * 8 + j] * dct_d[i * 8 + j] * mask[i][j];
             s_mask = sqrt(s_mask * s_gvar) / 32.f;
-            d_mask = sqrt(d_mask * d_gvar) / 32.f;
-            if (d_mask > s_mask)
-                s_mask = d_mask;
             for (i = 0; i < 8; i++) {
                 for (j = 0; j < 8; j++) {
                     float err;
```

**Comment by kylophone** [comment]
We cannot change the default PSNR-HVS weights since they are the currently used in the AOM CTC. We could potentially provide a way to switch to a different set of weights via a feature extractor option(s). I am not convinced that the extra complexity and overhead that this adds is worth it, but maybe you can convince me. Questions I have for you:

- Are you sure that your adjustments are not just overfitting to a particular data set?
- What is your usecase?

**Comment by igv** [comment]
I just want to fix this metric because in its current state it's pretty useless. I don't try to optimize it for tid2013, I just use it to test my improvements. What other good dataset can I use?
My usecase is trusting the results of this metric. Every time I see a comparison where this metric is used it looks very weird. With these adjustments the result scores look much saner and in line with VIF and DSSIM (I trust those metrics).

**Comment by igv** [comment]
I can see why Xiph's weights might be better for video, so adding these weights as an option (call it image-optimized?) is a better idea I think.

**Pull request closed without merging**
