### PR TITLE
github: remove workaround for macOS issues

### PR DESCRIPTION
**Pull request by 1480c1**
Fixes the current macOS issues

### CODE REVIEW

**Comment by 1480c1** [comment]
I think macOS is just cursed at this point https://github.com/1480c1/vmaf/runs/1561670926 https://github.com/Netflix/vmaf/runs/1561696026 same commit

**Comment by kylophone** [comment]
> I think macOS is just cursed at this point https://github.com/1480c1/vmaf/runs/1561670926 https://github.com/Netflix/vmaf/runs/1561696026 same commit

Yeah, those extra brew commands were added awhile back to work around a different brew issue. Should I merge this as-is, or is more work needed?

**Comment by 1480c1** [comment]
> > I think macOS is just cursed at this point https://github.com/1480c1/vmaf/runs/1561670926 https://github.com/Netflix/vmaf/runs/1561696026 same commit
> 
> Yeah, those extra brew commands were added awhile back to work around a different brew issue. Should I merge this as-is, or is more work needed?

I think more work/info is needed either on brew's side or github, so don't merge this one yet

**Comment by 1480c1** [comment]
https://github.com/actions/virtual-environments/issues/2248#issuecomment-746031542 it seems maybe a max of 24 hours now?

**Comment by 1480c1** [comment]
@kylophone seems the issues were resolved in the latest image

**Comment by kylophone** [comment]
Thank you, merged.

**Pull request merged**
