### PR TITLE
Fix, MacOS CI runners are all failing at the brew stage

### PR DESCRIPTION
**Pull request by kylophone**
WIP, our MacOS CI runners are all failing at the `brew` stage. Trying to debug and fix.

### CODE REVIEW

**Comment by kylophone** [comment]
^ @1480c1, fyi in case you've already seen/fixed this in some other repo.

**Comment by kylophone** [comment]
Oh, is this the same as https://github.com/AOMediaCodec/SVT-AV1/commit/d5ad67725b0190615eef35897acfc0fa0c73a08f?

**Comment by 1480c1** [comment]
Yeah, same issue/fix

**Comment by kylophone** [comment]
> Yeah, same issue/fix

Thanks. I'll take care of it.

**Pull request merged**
