### PR TITLE
Use stat struct instead of ftell to retrieve the file size

### LINKED ISSUE #349: vmafossexec 2GB input file limit
Using Windows 7 x64, and the executable from https://ci.appveyor.com/project/li-zhi/vmaf/build/artifacts, if the first (reference) YUV file is over 2GB, the application exits with "ftell failed".

The code is attempting to get the file length by seeking to the end, and asking for the position, and failing. It seems to be hitting the limit of a 32-bit system (long int max 2^31-1, i.e. ~ 2GB), but this should be a 64 bit compile so not have this limit.

I have an FFMpeg built with vmaf support that doesn't have this limit, and I'm sure people are running tests on files >2GB on other systems, so maybe something is wrong with the compiler options for the Windows compile available from the link above?

### PR DESCRIPTION
**Pull request by HolyWu**
Closes #349.

### CODE REVIEW

**Comment by HolyWu** [comment]
@li-zhi Your [55c36a8 commit](https://github.com/Netflix/vmaf/commits/master) showed an error on travis-ci. The travis-ci badge in https://github.com/Netflix/vmaf/blob/master/README.md also showed build error. So it's not my code failing the checks. What's the cause?

**Comment by li-zhi** [comment]
Thanks. Looking into it.

**Comment by christosbampis** [comment]
There is a fix now in master. @HolyWu can you please branch off from the latest master and put your changes? The updated PR should go through Travis. Let me know if you got any questions.

**Comment by HolyWu** [comment]
Rebased. Seems OK now.

**Comment by christosbampis** [comment]
sounds good, merged that in!

**Comment by li-zhi** [comment]
@HolyWu I would like to reach out to you regarding an issue of VMAF re-licensing. Would you please email me at zli@netflix.com with your personal email address? Thanks!

**Pull request merged**
