### PR TITLE
fix building error

### PR DESCRIPTION
**Pull request by XuShiSheng**
fix building error. "stdatomic.h" is missing in GCC-4.8. We use gnu&msc buildin fuctions instead of atomic_int in stdatomic.h. Problem mentioned in (#406)

### CODE REVIEW

**Comment by kylophone** [comment]
I think a prefer an approach similar to what `dav1d` has done on this: https://code.videolan.org/videolan/dav1d/-/blob/master/include/compat/gcc/stdatomic.h

**Comment by XuShiSheng** [comment]
ok, I changed modifications and follow what has been done in dav1d.

**Comment by kylophone** [comment]
Thanks for taking the time to fix that! I will take a look at this today.

**Comment by XuShiSheng** [comment]
hi, is there something awkward need to be change?

**Comment by kylophone** [comment]
> hi, is there something awkward need to be change?

Nope. Sorry about the delay. Merged.

**Pull request merged**
