### PR TITLE
Actions: Add windows workflow

### LINKED ISSUE #642: appveyor: Maximum allowed artifact storage size of 50000 Mb will be exceeded.
Our appveyor is out of artifact storage as of https://ci.appveyor.com/project/li-zhi/vmaf/builds/34577819. This has happened to me a few times in other repos. It is a real bummer, tbh. Last time this happened to me the solution was to open a ticket at appveyor asking for more storage. Not really a permanent solution, because it will happen again at some point in the future. So unless someone knows better (@1480c1, maybe you've encountered this again more recently than I have?), I guess there are two solutions:

- Open an appveyor ticket and ask for more storage. @li-zhi, this was registered under your personal account, looks like.

-  Move all Windows CI to Github Actions, discontinue use of appveyor.

My preference is for the latter, replacing appveyor.

### PR DESCRIPTION
**Pull request by 1480c1**
Adds a GitHub Actions workflow for windows to replace the appveyor, currently, 32-bit is disabled due to the vmaf score not being the same.

Currently builds vmaf with mingw-w64 and then builds it with FFmpeg to test vmaf output being correct

Closes #642

@kylophone do you want me to remove appveyor.yml in this pr as well?

### CODE REVIEW

**Comment by kylophone** [comment]
> @kylophone do you want me to remove appveyor.yml in this pr as well?
Yes, please. Get rid of the Appveyor badge in the README too.

**Comment by 1480c1** [comment]
Seems appveyor will continue to fail until @li-zhi removes it from his personal account, either that or I can add a dummy appveyor that just runs on no branch

**Comment by li-zhi** [comment]
Is there anything I need to do on my end? Could we simply remove the link
from the README page?

**Comment by 1480c1** [comment]
The link has been removed, but you will need to go to https://ci.appveyor.com/project/li-zhi/vmaf/settings/delete and delete it

**Comment by li-zhi** [comment]
Done!

**Comment by kylophone** [comment]
@1480c1, ready for this to be merged?

**Comment by 1480c1** [comment]
Yep

**Pull request merged**
