### PR TITLE
CUDA feature extraction

### PR DESCRIPTION
**Pull request by kylophone**
Replaces #1080.

### CODE REVIEW

**Comment by HunterAP23** [comment]
I know this was merged, but is there any guide on how to build libvmaf for Windows under MINGW64 MYSYS2 with CUDA? I'm not able to find any method of putting CUDA on MINGW64 MYSYS2, so building this with CUDA enabled for Windows doesn't seem possible at the moment, unless there's some alternative method of doing so that isn't documented.

For reference, I've also tried Ubuntu through WSL2 but that seems to have a lot of errors, and it's not possible to cross-compile from there anyways.

**Comment by kylophone** [comment]
I have not personally tried this with Windows yet, I have been developing on Linux only. Could you please make an issue, we should be able to support it.

**Comment by ehmkhay** [comment]
Does this PR implement CUDA pipeline to ffmpeg -lavfi for in-GPU nvdec>vmaf (in linux)?
(or is this still in development?)
Thanks!

**Comment by kylophone** [comment]
> Does this PR implement CUDA pipeline to ffmpeg -lavfi for in-GPU nvdec>vmaf (in linux)? (or is this still in development?) Thanks!

That work is in progress, you should see it on `ffmpeg-devel` soon.

**Comment by ehmkhay** [comment]
Brilliant, thanks!

**Comment by maxpain** [comment]
How to use cuda acceleration in vmaf today?

**Pull request merged**
